### ISSUE TITLE
How did you get the NDI SDK to work with visionOS?

### ISSUE THREAD

**Issue by otanl** [gwangyu-lee/iXR-OSC-NDI#1]
This isn't directly related to the repository, but rather a question about visionOS apps. How did you make the NDI SDK compatible with visionOS? Alternatively, is there a way to make the iOS version of the SDK compatible?

**Comment by gwangyu-lee** [comment]
NDI SDK for visionOS is available now. Download the latest version of NDI SDK. And I used klakNDI with unity. I opened the issue and wrote about using NDI SDK with visionOS. Please check here. [https://github.com/keijiro/KlakNDI/issues/203](https://github.com/keijiro/KlakNDI/issues/203)

**Comment by otanl** [comment]
Excuse me, but when I install the SDK for NDI v6, VisionOS is not included.

**Comment by gwangyu-lee** [comment]
Omg, I'm so sorry. I was confused because I tried too many times in different ways. I just copied and changed the name of `libndi_ios.a` to `libndi_visionos.a`. And made a new folder `visionOS`. I completely forgot about it and I thought visionOS SDK was released.

**Comment by gwangyu-lee** [comment]
I just updated the issue in the klakNDI repository and rechecked if using the `libndi_ios.a` was correct. It works fine when I rebuild it. If it doesn't work, please let me know.

**Comment by otanl** [comment]
Thank you. I gave that method a quick try, but it didn’t work for me (it could have been because I was using Swift, or maybe it was just my own mistake). I'll give it another shot.

Thanks again, I really appreciate your help. I’ve also purchased your app, of course.

**Comment by gwangyu-lee** [comment]
Thank you!!

**Comment by gwangyu-lee** [comment]
Hi! I've uploaded KlakNDI visionOS demo project(unity). If you are interested, please check here. https://github.com/gwangyu-lee/KlakNDI-visionOS-Demo

**Comment by kringelbach** [comment]
@otanl did you get it to work with Swift? The "built for 'iOS'" is an error in a standard visionOS Xcode project and not a warning.
